// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: grpc/svr/app_manager.proto

package svr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppName 服务名称请求参数
type AppName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 服务名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppName) Reset() {
	*x = AppName{}
	mi := &file_grpc_svr_app_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppName) ProtoMessage() {}

func (x *AppName) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_svr_app_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppName.ProtoReflect.Descriptor instead.
func (*AppName) Descriptor() ([]byte, []int) {
	return file_grpc_svr_app_manager_proto_rawDescGZIP(), []int{0}
}

func (x *AppName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListReply 字符串列表响应
type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 结果列表
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`     // 错误信息，为空表示成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_grpc_svr_app_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_svr_app_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_grpc_svr_app_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ListReply) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// StatusReply 状态查询响应
type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 服务状态
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`       // 错误信息，为空表示成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_grpc_svr_app_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_svr_app_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_grpc_svr_app_manager_proto_rawDescGZIP(), []int{2}
}

func (x *StatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// BoolReply 布尔值响应
type BoolReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`  // 操作是否成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"` // 响应消息或错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolReply) Reset() {
	*x = BoolReply{}
	mi := &file_grpc_svr_app_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolReply) ProtoMessage() {}

func (x *BoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_svr_app_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolReply.ProtoReflect.Descriptor instead.
func (*BoolReply) Descriptor() ([]byte, []int) {
	return file_grpc_svr_app_manager_proto_rawDescGZIP(), []int{3}
}

func (x *BoolReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BoolReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_grpc_svr_app_manager_proto protoreflect.FileDescriptor

const file_grpc_svr_app_manager_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/svr/app_manager.proto\x12\x03svr\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\aAppName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\tListReply\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"7\n" +
	"\vStatusReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"-\n" +
	"\tBoolReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xe4\x03\n" +
	"\x11AppManagerService\x127\n" +
	"\rGetAllAppName\x12\x16.google.protobuf.Empty\x1a\x0e.svr.ListReply\x12(\n" +
	"\x06Status\x12\f.svr.AppName\x1a\x10.svr.StatusReply\x12%\n" +
	"\x05Start\x12\f.svr.AppName\x1a\x0e.svr.BoolReply\x12$\n" +
	"\x04Stop\x12\f.svr.AppName\x1a\x0e.svr.BoolReply\x12'\n" +
	"\aReStart\x12\f.svr.AppName\x1a\x0e.svr.BoolReply\x122\n" +
	"\bStartAll\x12\x16.google.protobuf.Empty\x1a\x0e.svr.ListReply\x121\n" +
	"\aStopAll\x12\x16.google.protobuf.Empty\x1a\x0e.svr.ListReply\x123\n" +
	"\tStatusAll\x12\x16.google.protobuf.Empty\x1a\x0e.svr.ListReply\x12'\n" +
	"\aSyncApp\x12\f.svr.AppName\x1a\x0e.svr.BoolReply\x121\n" +
	"\aSyncAll\x12\x16.google.protobuf.Empty\x1a\x0e.svr.BoolReplyB*Z(github.com/JJApplication/Apollo/grpc/svrb\x06proto3"

var (
	file_grpc_svr_app_manager_proto_rawDescOnce sync.Once
	file_grpc_svr_app_manager_proto_rawDescData []byte
)

func file_grpc_svr_app_manager_proto_rawDescGZIP() []byte {
	file_grpc_svr_app_manager_proto_rawDescOnce.Do(func() {
		file_grpc_svr_app_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_svr_app_manager_proto_rawDesc), len(file_grpc_svr_app_manager_proto_rawDesc)))
	})
	return file_grpc_svr_app_manager_proto_rawDescData
}

var file_grpc_svr_app_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_svr_app_manager_proto_goTypes = []any{
	(*AppName)(nil),       // 0: svr.AppName
	(*ListReply)(nil),     // 1: svr.ListReply
	(*StatusReply)(nil),   // 2: svr.StatusReply
	(*BoolReply)(nil),     // 3: svr.BoolReply
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_grpc_svr_app_manager_proto_depIdxs = []int32{
	4,  // 0: svr.AppManagerService.GetAllAppName:input_type -> google.protobuf.Empty
	0,  // 1: svr.AppManagerService.Status:input_type -> svr.AppName
	0,  // 2: svr.AppManagerService.Start:input_type -> svr.AppName
	0,  // 3: svr.AppManagerService.Stop:input_type -> svr.AppName
	0,  // 4: svr.AppManagerService.ReStart:input_type -> svr.AppName
	4,  // 5: svr.AppManagerService.StartAll:input_type -> google.protobuf.Empty
	4,  // 6: svr.AppManagerService.StopAll:input_type -> google.protobuf.Empty
	4,  // 7: svr.AppManagerService.StatusAll:input_type -> google.protobuf.Empty
	0,  // 8: svr.AppManagerService.SyncApp:input_type -> svr.AppName
	4,  // 9: svr.AppManagerService.SyncAll:input_type -> google.protobuf.Empty
	1,  // 10: svr.AppManagerService.GetAllAppName:output_type -> svr.ListReply
	2,  // 11: svr.AppManagerService.Status:output_type -> svr.StatusReply
	3,  // 12: svr.AppManagerService.Start:output_type -> svr.BoolReply
	3,  // 13: svr.AppManagerService.Stop:output_type -> svr.BoolReply
	3,  // 14: svr.AppManagerService.ReStart:output_type -> svr.BoolReply
	1,  // 15: svr.AppManagerService.StartAll:output_type -> svr.ListReply
	1,  // 16: svr.AppManagerService.StopAll:output_type -> svr.ListReply
	1,  // 17: svr.AppManagerService.StatusAll:output_type -> svr.ListReply
	3,  // 18: svr.AppManagerService.SyncApp:output_type -> svr.BoolReply
	3,  // 19: svr.AppManagerService.SyncAll:output_type -> svr.BoolReply
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_svr_app_manager_proto_init() }
func file_grpc_svr_app_manager_proto_init() {
	if File_grpc_svr_app_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_svr_app_manager_proto_rawDesc), len(file_grpc_svr_app_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_svr_app_manager_proto_goTypes,
		DependencyIndexes: file_grpc_svr_app_manager_proto_depIdxs,
		MessageInfos:      file_grpc_svr_app_manager_proto_msgTypes,
	}.Build()
	File_grpc_svr_app_manager_proto = out.File
	file_grpc_svr_app_manager_proto_goTypes = nil
	file_grpc_svr_app_manager_proto_depIdxs = nil
}
