name: Apollo builder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  

env:
  GO111MODULE: on
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Start
      run: echo "start to build Apollo"
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
