
name: Apollo release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  

env:
  GO111MODULE: on
  GONOSUMDB: "*"
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Get date
      run: echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Start
      run: echo "start to build Apollo"
      
    - name: Build
      run: go build -mod=mod -ldflags='-w -s' -trimpath -v -o apollo

    - name: Done
      run: echo "build success"

    - name: Release Name
      run: |
        echo "start to create release name from ${{ github.ref }}"
        echo "RELEASE=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

    - name: CreateMD
      run: |
        touch ${{ github.workspace }}-CHANGELOG.txt
        echo "" > ${{ github.workspace }}-CHANGELOG.txt
        echo "# 🚀 New Release" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "## 🤖 Published by bot" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "build at ${{ env.DATE }}" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "## 📄 What‘s new" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "${{ github.event.head_commit.message }}" >> ${{ github.workspace }}-CHANGELOG.txt

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Apollo ${{ env.RELEASE }}
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        draft: false
        prerelease: false
        files: |
          apollo
          LICENSE
          conf/apollo.pig
          conf/middleware.pig
          README.md
